/**
 * Build-time UI bundler.
 *
 * Runs `Bun.build` once (with `bun-plugin-tailwind`) over the browser entry
 * `src/ui/main.tsx`, then emits the resulting JS + CSS as a generated TS module
 * `src/core/ui-bundle.generated.ts` (`export const uiBundle = { js, css }`).
 *
 * Moving the bundle to build time is what lets both distribution paths work:
 *   - `bun build --compile` embeds ordinary source (the generated module) into a
 *     self-contained binary — no runtime bundler, no source-tree read.
 *   - a global install ships the generated module and never needs the
 *     `bun-plugin-tailwind` devDependency at runtime.
 *
 * Paths are resolved from `import.meta.dir` so the script runs from any CWD.
 * Throws loudly if the build fails or either artifact is missing, so a broken
 * bundle can never be silently committed.
 */

import tailwind from "bun-plugin-tailwind";

const entry = `${import.meta.dir}/../src/ui/main.tsx`;
const outPath = `${import.meta.dir}/../src/core/ui-bundle.generated.ts`;

const result = await Bun.build({
  entrypoints: [entry],
  target: "browser",
  minify: false,
  plugins: [tailwind],
  define: { "process.env.NODE_ENV": '"production"' },
});

if (!result.success) {
  const msg = result.logs.map((l) => String(l)).join("\n");
  throw new Error(`UI bundle build failed:\n${msg}`);
}

// Select the JS entry by kind (robust if code-splitting ever emits extra `.js`
// chunks), falling back to extension; the stylesheet is a `.css` asset.
const jsArtifact =
  result.outputs.find((o) => o.kind === "entry-point") ??
  result.outputs.find((o) => o.path.endsWith(".js"));
const cssArtifact = result.outputs.find((o) => o.path.endsWith(".css"));

if (jsArtifact === undefined) {
  throw new Error("UI bundle produced no JS output artifact");
}
if (cssArtifact === undefined) {
  throw new Error("UI bundle produced no CSS output artifact (Tailwind plugin?)");
}

const js = await jsArtifact.text();
const css = await cssArtifact.text();

const module = `/**
 * AUTO-GENERATED by scripts/build-ui.ts — DO NOT EDIT BY HAND.
 *
 * The pre-built browser UI (Ring 2): JS entry bundle + Tailwind-emitted CSS.
 * Regenerate with \`bun run build\`. Git-ignored; produced fresh at build time.
 */

export const uiBundle = {
  js: ${JSON.stringify(js)},
  css: ${JSON.stringify(css)},
} as const;
`;

await Bun.write(outPath, module);

process.stderr.write(
  `build-ui: wrote ${outPath} (js ${js.length} bytes, css ${css.length} bytes)\n`,
);
