/**
 * Build-time Snapshot offline-runtime bundler (Story 6.3).
 *
 * Runs `Bun.build` once over the browser entry `src/snapshot/runtime.ts` and emits the
 * resulting JS as a generated TS module `src/core/snapshot-bundle.generated.ts`
 * (`export const snapshotBundle = { js }`). The Core origin serves this at
 * `/snapshot-runtime.js`; Ring 2 fetches it same-origin at export time and inlines it into the
 * self-contained Snapshot `.html`.
 *
 * Ring discipline: `runtime.ts` imports ONLY `src/shared/` + `src/sandbox/render.ts` + the
 * render libraries (`@observablehq/plot`, `micromark`) — never `src/core`, `src/ui`, `ai`, or a
 * token/secret. The bundle is data-free renderer code (mirrors `/guest.js`).
 *
 * Mirrors `scripts/build-sandbox.ts`: paths resolve from `import.meta.dir`; throws loudly if
 * the build fails or the JS artifact is missing.
 */

const entry = `${import.meta.dir}/../src/snapshot/runtime.ts`;
const outPath = `${import.meta.dir}/../src/core/snapshot-bundle.generated.ts`;

const result = await Bun.build({
  entrypoints: [entry],
  target: "browser",
  // Minify: Observable Plot + micromark ship inside the inlined Snapshot runtime, so trimming
  // the bundle keeps every exported `.html` file lean.
  minify: true,
  define: { "process.env.NODE_ENV": '"production"' },
});

if (!result.success) {
  const msg = result.logs.map((l) => String(l)).join("\n");
  throw new Error(`Snapshot runtime bundle build failed:\n${msg}`);
}

const jsArtifact =
  result.outputs.find((o) => o.kind === "entry-point") ??
  result.outputs.find((o) => o.path.endsWith(".js"));

if (jsArtifact === undefined) {
  throw new Error("Snapshot runtime bundle produced no JS output artifact");
}

const js = await jsArtifact.text();

const module = `/**
 * AUTO-GENERATED by scripts/build-snapshot.ts — DO NOT EDIT BY HAND.
 *
 * The pre-built offline Snapshot runtime (browser JS inlined into an exported .html).
 * Regenerate with \`bun run build\`. Git-ignored; produced fresh at build time.
 */

export const snapshotBundle = {
  js: ${JSON.stringify(js)},
} as const;
`;

await Bun.write(outPath, module);

process.stderr.write(`build-snapshot: wrote ${outPath} (js ${js.length} bytes)\n`);
