/**
 * Build-time Ring 3 guest bundler (Story 5.5).
 *
 * Runs `Bun.build` once over the browser entry `src/sandbox/guest.ts` and emits the
 * resulting JS as a generated TS module `src/core/sandbox-bundle.generated.ts`
 * (`export const sandboxBundle = { js }`). The sandbox origin serves this at
 * `/guest.js`; there is NO CSS (the guest doc's own inline `<style>` is all it needs).
 *
 * Same rationale as `scripts/build-ui.ts`: moving the bundle to build time lets
 * `bun build --compile` embed ordinary source into a self-contained binary and lets a
 * global install ship the generated module without a runtime bundler.
 *
 * Ring discipline: `guest.ts` imports ONLY `src/shared/`, so this bundle can never
 * carry Core/UI code, an `ai`/`@ai-sdk` dependency, a key, or a token.
 *
 * Paths are resolved from `import.meta.dir` so the script runs from any CWD. Throws
 * loudly if the build fails or the JS artifact is missing.
 */

const entry = `${import.meta.dir}/../src/sandbox/guest.ts`;
const outPath = `${import.meta.dir}/../src/core/sandbox-bundle.generated.ts`;

const result = await Bun.build({
  entrypoints: [entry],
  target: "browser",
  minify: false,
  define: { "process.env.NODE_ENV": '"production"' },
});

if (!result.success) {
  const msg = result.logs.map((l) => String(l)).join("\n");
  throw new Error(`Sandbox guest bundle build failed:\n${msg}`);
}

const jsArtifact =
  result.outputs.find((o) => o.kind === "entry-point") ??
  result.outputs.find((o) => o.path.endsWith(".js"));

if (jsArtifact === undefined) {
  throw new Error("Sandbox guest bundle produced no JS output artifact");
}

const js = await jsArtifact.text();

const module = `/**
 * AUTO-GENERATED by scripts/build-sandbox.ts — DO NOT EDIT BY HAND.
 *
 * The pre-built Ring 3 guest runtime (cross-origin sandbox JS). Regenerate with
 * \`bun run build\`. Git-ignored; produced fresh at build time.
 */

export const sandboxBundle = {
  js: ${JSON.stringify(js)},
} as const;
`;

await Bun.write(outPath, module);

process.stderr.write(`build-sandbox: wrote ${outPath} (js ${js.length} bytes)\n`);
