/**
 * Build-time version baker.
 *
 * Reads `package.json`'s `version` and emits it as a generated TS module
 * `src/core/version.generated.ts` (`export const VERSION = "…" as const;`),
 * mirroring `scripts/build-ui.ts`'s generated-module pattern and for the same
 * reason: a `bun build --compile` binary has no source tree and no
 * `package.json` to read at run time, so the version must become ordinary
 * source before compiling.
 *
 * Resolved via `import.meta.url` (not `process.cwd()`), so the script runs
 * correctly from any CWD. Throws loudly (never `process.exit`) on any
 * failure, so a missing/malformed version can never be silently baked in.
 */

const packageJsonUrl = new URL("../package.json", import.meta.url);
const raw = await Bun.file(packageJsonUrl).json();

const version = raw.version;
// Anchored at both ends: `major.minor.patch` with an optional `-prerelease`
// and/or `+build` tail, and NOTHING after it. An unanchored pattern would
// bake trailing garbage (`1.2.3.4`, `1.2.3 oops`) verbatim into VERSION.
if (typeof version !== "string" || !/^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?(?:\+[0-9A-Za-z.-]+)?$/.test(version)) {
  throw new Error(
    `build-version: package.json 'version' must be a non-empty semver-like string, got ${JSON.stringify(version)}`,
  );
}

// Same `import.meta.url`-relative resolution as the package.json read above, so
// the script is CWD-independent end to end (no string-concat path building).
const outPath = new URL("../src/core/version.generated.ts", import.meta.url);

const module = `/**
 * AUTO-GENERATED by scripts/build-version.ts — DO NOT EDIT BY HAND.
 *
 * The package version, baked in at build time. A \`--compile\` binary has no
 * package.json to read. Regenerate with \`bun run build\`. Git-ignored.
 */

export const VERSION = ${JSON.stringify(version)} as const;
`;

await Bun.write(outPath, module);

process.stderr.write(`build-version: wrote ${outPath.pathname} (VERSION ${JSON.stringify(version)})\n`);
