/**
 * Build-time Live Report runtime bundler (Story 6.4).
 *
 * Runs `Bun.build` once over the browser entry `src/live-report/runtime.ts` and emits the
 * resulting JS as a generated TS module `src/core/live-report-bundle.generated.ts`
 * (`export const liveReportBundle = { js }`). The Core origin serves this at
 * `/live-report-runtime.js` (open, data-free) and inlines it into the served `/live/<id>` page;
 * Ring 2 fetches it same-origin at export time and inlines it into the portable `.html`.
 *
 * Ring discipline: `runtime.ts` imports ONLY `src/shared/` + `src/sandbox/render.ts` + the
 * render libraries (`@observablehq/plot`) + a tiny inline same-origin fetch — never `src/core`,
 * `src/ui`, `ai`, `recharts`, or a token/secret. The bundle is data-free renderer code.
 *
 * Mirrors `scripts/build-snapshot.ts`: paths resolve from `import.meta.dir`; throws loudly if
 * the build fails or the JS artifact is missing.
 */

const entry = `${import.meta.dir}/../src/live-report/runtime.ts`;
const outPath = `${import.meta.dir}/../src/core/live-report-bundle.generated.ts`;

const result = await Bun.build({
  entrypoints: [entry],
  target: "browser",
  // Minify: Observable Plot ships inside the inlined Live Report runtime, so trimming the
  // bundle keeps every exported `.html` file lean.
  minify: true,
  define: { "process.env.NODE_ENV": '"production"' },
});

if (!result.success) {
  const msg = result.logs.map((l) => String(l)).join("\n");
  throw new Error(`Live Report runtime bundle build failed:\n${msg}`);
}

const jsArtifact =
  result.outputs.find((o) => o.kind === "entry-point") ??
  result.outputs.find((o) => o.path.endsWith(".js"));

if (jsArtifact === undefined) {
  throw new Error("Live Report runtime bundle produced no JS output artifact");
}

const js = await jsArtifact.text();

const module = `/**
 * AUTO-GENERATED by scripts/build-live-report.ts — DO NOT EDIT BY HAND.
 *
 * The pre-built Live Report runtime (browser JS inlined into an exported .html and the
 * Core-served /live/<id> page). Regenerate with \`bun run build\`. Git-ignored; produced
 * fresh at build time.
 */

export const liveReportBundle = {
  js: ${JSON.stringify(js)},
} as const;
`;

await Bun.write(outPath, module);

process.stderr.write(`build-live-report: wrote ${outPath} (js ${js.length} bytes)\n`);
